FROM oven/bun:1.2-alpine

WORKDIR /app

COPY src/backend/package.json /app/package.json
RUN bun install --frozen-lockfile

COPY src/backend /app

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "dist/main.js"]
