FROM oven/bun:1.2-alpine

WORKDIR /app

COPY src/frontend/package.json /app/package.json
RUN bun install --frozen-lockfile

COPY src/frontend /app

RUN bun run build

EXPOSE 4173

CMD ["bun", "run", "preview", "--host", "0.0.0.0", "--port", "4173"]

